repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.1  # Check for the latest version on GitHub
    hooks:
      - id: terraform_fmt
        args: ["--recursive"]
        files: ^terraform/
      - id: terraform_validate
        args: ["--recursive"]
        files: ^terraform/
      - id: terraform_tflint
        args: ["--recursive"]
        files: ^terraform/
      - id: terraform_docs
        args: ["--recursive"]
        files: ^terraform/
      - id: terraform_tfsec
        args: ["--recursive"]
        files: ^terraform/