apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    privateKeySecretRef:
      name: issuer
    solvers:
    - dns01:
        route53:
          hostedZoneID: Z00490453R6ROI5MQ7P2E
          region: eu-west-2
      selector:
        dnsZones:
        - "eks.riajul-devops.com"
    - http01:
        ingress:
          class:  nginx