apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deploy
  labels:
    app: game-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-pods
  template:
    metadata:
      labels:
        app: game-pods
    spec:
      containers:
      - name: game-2048
        image: 706490763179.dkr.ecr.eu-west-2.amazonaws.com/2048-game
        ports:
        - containerPort: 3000

--- 

apiVersion: v1 
kind: Service
metadata:
  name: game-2048-service
spec:
  selector:
    app: game-pods
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game-ingress
  annotations:
    cert-manager.io/cluster-issuer: "issuer"
spec:
  ingressClassName: nginx
  rules:
  - host: game.eks.riajul-devops.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: game-2048-service
            port: 
              number: 80
  tls:
  - hosts:
    - game.eks.riajul-devops.com
    secretName: game-app-tls
