name: tear-down
on: 
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


jobs:

    helm-uninstall:
      runs-on: ubuntu-latest

      steps:

      - name: Make cleanup script executable
        run: chmod +x scripts/cleanup.sh
        

      - name: Checkout the repository to the runner
        uses: actions/checkout@v3


      - name: helm uninstall
        run: .scripts/cleanup.sh
        env:
          REGION: ${{ vars.REGION }}
          CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}


    terraform_destroy:
      runs-on: ubuntu-latest
      needs: helm-uninstall
      defaults:

        run:
          working-directory: Terraform

      steps:

      - name: Checkout the repository to the runner
        uses: actions/checkout@v3


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.12.2

      
      - name: Terraform Init
        run: terraform init


      - name: Terraform Destroy
        run: terraform destroy -auto-approve